# Generated by Django 5.0.6 on 2024-10-04 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='food_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.fooditem'),
        ),
    ]
