# Generated by Django 5.1.1 on 2024-10-28 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_review_order_review_food_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expiry_date',
        ),
    ]
